apiVersion: v1
kind: Service
metadata:
  labels:
    app: keda-app
  name: keda-app
  namespace: keda-demo
spec:
  clusterIP: 172.31.102.180
  clusterIPs:
  - 172.31.102.180
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: keda-app
  sessionAffinity: None
  type: ClusterIP
